notifications:
  email:
    on_success: never
    on_failure: change

dist: trusty

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    packages:
      # by default the container VMs have Git 1.9.1, ermagherd...
      - git-all
      # this is required to compile keytar
      - libsecret-1-dev
      # this package is essential for testing Electron in a headless fashion
      # https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md
      - xvfb
      # packages required for electron-installer-debian
      - fakeroot
      - dpkg
      # packages required for electron-installer-redhat
      - rpm
      # packages required for electron-installer-appimage
      - xz-utils
      - xorriso

branches:
  only:
    - master
    - /^__release-.*/

language: node_js
node_js:
  - "8.9.0"

cache:
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron
    - .eslintcache

install:
  - npm install -g yarn@1.3.2
  - yarn install --force

script:
  - yarn lint
  - yarn build:prod
  - yarn test:setup
  - yarn test

after_failure:
  - yarn test:review
